### PR TITLE
Bookmarking support

### PR DESCRIPTION
**Pull request by broadwell**
Here is the promised bookmarks PR against the current version of develop. Things to note:
- `App.js` builds the proper form settings when a bookmark is detected in the query string and eventually passes these settings on to the form and the scriptchart/tab components.
- `BookmarkModal.js` has the code for the popup bookmarking modal.
- `DashTabs.js` has the actual Bookmark button; when clicked, it generates a bookmark URL from the current settings of the scriptchart and displays the modal.
- `ManuscriptForm.js` has gotten a bit more complicated because it needs handle two possible types of form updates: 1) normal changes made by clicking buttons, and 2) a bulk render-time update based on bookmark settings coming from the parent App (via the formData props). It also must support users making further config option changes via the form after loading a bookmark. It does all this, though perhaps not elegantly.

A final caveat: `react-modal` binds to a top-level component of the DOM so that the modal popup is registered correctly by accessibility devices, but this plays havoc with the Jest testing setup. At present, 4 tests fail due to this entirely benign bug, but I'm at a loss as to how to fix it or even just get around it -- see also https://github.com/reactjs/react-modal/issues/632.

### CODE REVIEW

**Comment by simonwiles** [comment]
One initial observation: rows and columns that are hidden from the chart are not taken into account in the bookmark -- they are included in the bookmark and shown when it is loaded.  Whether this needs to be "fixed" is an open question.

**Comment by broadwell** [comment]
Yeah re: hidden rows and letters, it seemed like it would take a lot of work to implement a feature that I doubt many people would use (though I could be wrong on both counts) -- instead of sharing a bookmark with hidden rows/columns, they could just share a bookmark that doesn't have those rows/columns in the first place.

**Comment by broadwell** [comment]
Re: the bookmark URL format, now I kinda want to fold the "examples=" key into "opts=", so that the default settings would have a bookmark opts string of "opts=3bmhl" instead of "examples=3&opts=bmhl". Previously there seemed to be some merit to making this setting more legible in the URL, as with the letters and manuscripts, but I'm not feeling it anymore. Thoughts?

**Comment by simonwiles** [comment]
> Yeah re: hidden rows and letters, it seemed like it would take a lot of work to implement a feature that I doubt many people would use (though I could be wrong on both counts) -- instead of sharing a bookmark with hidden rows/columns, they could just share a bookmark that doesn't have those rows/columns in the first place.

I lean the other way on both counts, tbh.  But yes, the workaround is simple.  Voting to leave as is until someone complains :)

**Comment by simonwiles** [comment]
> Re: the bookmark URL format, now I kinda want to fold the "examples=" key into "opts=", so that the default settings would have a bookmark opts string of "opts=3bmhl" instead of "examples=3&opts=bmhl". Previously there seemed to be some merit to making this setting more legible in the URL, as with the letters and manuscripts, but I'm not feeling it anymore. Thoughts?

I'm fine either way with this.  My only concern with this is once the site is "in-use", however that's defined, any changes to this will break existing links unless we commit to maintaining backwards-compatibility here.

**Pull request merged**
